branches:
    only:
        - gh-pages
language:
    python
python:
  - "2.7"
    # command to install dependencies
install:
  "pip install -r requirements.txt"
script:
  - make show
after_sucess:
    bash deploy.sh
notifications:
    webhooks: http://hooktwitterblog.herokuapp.com/travis
