branches:
  only: gh-pages
language: python
python:
- '2.7'
install: pip install -r requirements.txt
script:
- make show
notifications:
  webhooks: http://hooktwitterblog.herokuapp.com/travis
after_success: bash deploy.sh
env:
  global:
    secure: E8v/sEAAEHvXIaA6jlY3PIXckWF34h66G9eWLo4Sog94KgLM3iZ///RIQ2J5RzEVEoz1t8KpQ7bUtStCN/tLs9/HJD10CPAdsAuEvmwK3p30pFNyERLsmiAvMoPAj9ueU+h/UEpmhYajAb0iqBXmaOvHwOiDMP5ME9mX90/UIk4=
