branches:
  only: src
language: python
python:
  - "2.7"
    # command to install dependencies
install:
  "pip install -r requirements.txt"
script: pelican -s publishconf.py
after_success: bash deploy.sh
notifications:
  webhooks: http://hooktwitterblog.herokuapp.com/travis
